version: '3.8'

services:
  # CORS-enabled proxy for Presidio Analyzer
  presidio-analyzer-proxy:
    image: nginx:alpine
    container_name: pii-presidio-analyzer-proxy
    ports:
      - "5001:80"
    volumes:
      - ./config/nginx-analyzer.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - presidio-analyzer
    restart: unless-stopped
    networks:
      - presidio-network

  presidio-analyzer:
    image: mcr.microsoft.com/presidio-analyzer:latest
    container_name: pii-presidio-analyzer
    expose:
      - "3000"
    environment:
      - PRESIDIO_ANALYZER_PORT=3000
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - presidio-network

  # CORS-enabled proxy for Presidio Anonymizer
  presidio-anonymizer-proxy:
    image: nginx:alpine
    container_name: pii-presidio-anonymizer-proxy
    ports:
      - "5002:80"
    volumes:
      - ./config/nginx-anonymizer.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - presidio-anonymizer
    restart: unless-stopped
    networks:
      - presidio-network

  presidio-anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    container_name: pii-presidio-anonymizer
    expose:
      - "3000"
    environment:
      - PRESIDIO_ANONYMIZER_PORT=3000
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - presidio-network

networks:
  presidio-network:
    driver: bridge